name: Build

on: [push]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-latest]
        # Ubuntu build fails due to undefined reference to `pcap_offline_read'.
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install libpcap headers on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get install libpcap-dev

      - name: Build
        run: ./configure && make

      - name: Test
        run: ./tcptrace
